### ISSUE TITLE
Set up fuzzing tests

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs-redirects-file#12]
Ref. https://go.dev/security/fuzz/

We could use text fixture from https://github.com/ipfs/specs/pull/290 + Cloudflare and Netlify docs as seeds.

**Comment by lidel** [comment]
@justincjohnson this is also a precaution, I'd like us to be able to run a fuzzing test before we ship to production.

**Comment by justindotpub** [comment]
I have an initial implementation of fuzzing for you @lidel.  It led me to add more validation logic on the from and to paths, so that I had more errors I could check for.  Let me know what you think.
