### ISSUE TITLE
Remove forced redirects (no shadowing on IPFS)

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs-redirects-file#4]
https://github.com/ipfs/specs/pull/290 states that we don't support forced redirects because `_redirects`  is looked up only when requested content path is not present in the DAG.

@justincjohnson mind cleaning this up? :pray: 

- [x] removing [Forced](https://github.com/ipfs-shipyard/go-ipfs-redirects/blob/main/redirects.go#L33-L35) and all its uses in code and README examples, so it is not confusing people who use this library and expect it to work
- [x] return human-readable error when a redirect is defined with `!` (forced flag), explaining forced redirects (and ["shadowing"](https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing)) are not supported by IPFS gateways

**Comment by justindotpub** [comment]
Addressed in https://github.com/ipfs-shipyard/go-ipfs-redirects/pull/7.  Added you as reviewer.
